version: 2
jobs:
  build:    
    docker:
      - image: cirrusci/flutter:stable

    branches:
      only: master

    steps:
      - checkout
      - run:
          name: Update submodules
          command: |
              git submodule init
              git submodule update --remote

      - run:
          name: Run Flutter doctor
          command: flutter doctor

      - run:
          name: Run the application tests
          command: flutter test

      - run:
          name: Build the Android version
          command: flutter build apk 

      - run:
          name: Copy APK
          command: |
              mkdir -p /artifacts && cp build/app/outputs/apk/release/app-release.apk /artifacts

      - store_artifacts:
          path: /artifacts
