version: 2
jobs:
  build:    
    docker:
      - image: cirrusci/flutter:stable

    branches:
      only: master

    steps:
      - checkout
      - run:
          name: Update submodules
          command: |
              git submodule init
              git submodule update --remote

      - run:
          name: Run Flutter doctor
          command: flutter doctor

      - run:
          name: Run the application tests
          command: flutter test

      - run:
          name: Disable predexing for build speed
          command: |
              mkdir -p ~/.gradle && cat <<'EOF' > ~/.gradle/init.gradle
              allprojects {
                  project.plugins.whenPluginAdded { plugin ->
                      if ("com.android.build.gradle.AppPlugin".equals(plugin.class.name)) {
                          println "Disable pre-dexing for module ${project.name}"
                          project.android.dexOptions.preDexLibraries = false
                      } else if ("com.android.build.gradle.LibraryPlugin".equals(plugin.class.name)) {
                          println "Disable pre-dexing for module ${project.name}"
                          project.android.dexOptions.preDexLibraries = false
                      }
                  }
              }
              EOF

      - restore_cache:
          keys:
              - android-sdk

      - run:
          name: Build the Android version
          command: flutter build apk 

      - save_cache:
          key: android-sdk
          paths:
              - /opt/android-sdk-linux

      - run:
          name: Copy APK
          command: |
              sudo mkdir -p /artifacts && sudo chown "$(whoami)" /artifacts && cp build/app/outputs/apk/release/app-release.apk /artifacts

      - store_artifacts:
          path: /artifacts
